name: Release Pipeline

on:
  release:
    types: [ published ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4

    - name: Archive library
      run: |
        tar -czvf vpnclient-linux.tar.gz -C build libvpnclient_engine.a

    - name: Create DEB package
      run: |
        sudo apt-get install -y dh-make debhelper
        mkdir -p debian/usr/lib
        cp build/libvpnclient_engine.a debian/usr/lib/
        dh_make --createorig -s -y
        dpkg-buildpackage -us -uc

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: vpnclient-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
